apiVersion: apps/v1
metadata: 
   name: orders
   namespace: development
kind: Deployment
spec:
   selector:
      matchLabels:
         app: orders
   replicas: 4
   template:
     metadata:
        labels:
           app: orders
     spec:
       containers:
       - name: orders
         image: gcr.io/gkemhcs-eswari/orders
         ports:
         - containerPort: 8080
 
