apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRestrictNamespaces
metadata:
   name: restrict-namespace
spec:
    enforcementAction: deny
    parameters:
      restrictedNamespaces:
      - "kube-engine"
      - "cloud"
      - "gke"
